gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Escuela de Hackers 2016
description: Prototyping starter kit for Jekyll

baseurl: /

# Build settings
markdown: kramdown
